language: java

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk11

addons:
  # Required to avoid openjdk7 buffer overflow:
  # https://github.com/travis-ci/travis-ci/issues/5227
  hosts:
    - myshorthost
  hostname: myshorthost

before_install:
  - sudo apt-get -qq update
  # This package is needed by the jaxwscommons-81 IT (see Github issue #18)
  - sudo apt-get install -y gsettings-desktop-schemas

install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "mvn --show-version --errors --batch-mode validate dependency:go-offline"

script: "mvn --show-version --errors --batch-mode -Prun-its clean verify -Dittest.debug=false -Dinvoker.streamLogs=true"

cache:
  directories:
    - $HOME/.m2

branches:
  except:
    - gh-pages
